### ISSUE TITLE
Cannot run sample code on macOS

### ISSUE THREAD

**Issue by melMass** [taichi-dev/taichi_houdini#17]
Hello Trying to run the doc example:

```python
import taichi as ti
ti.init()
from fractal import fractalClass
f = fractalClass(512)
f.draw()
```

results in the following error:
```ruby
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user-14/Library/Preferences/houdini/19.0/taichi_houdini/Libs/python/fractal.py", line 26, in draw
    gui = ti.GUI("Julia Set", res=(self.res * 2, self.res))
  File "/Users/user-14/Library/Preferences/houdini/19.0/taichi_houdini/bundled-packages/taichi/misc/gui.py", line 95, in __init__
    fast_gui, fast_buf)
RuntimeError: Caught an unknown exception!
```

**Comment by YuCrazing** [comment]
Thanks for reporting! Can you provide more information about your OS?  It seems that you are using MacOS or Windows.

**Comment by melMass** [comment]
Thanks for the quick reply!
I am indeed on macOS.
For what it worth I can run taichi_blend without issue.

I actually used the same method as taichi_blend to bundle "external" package this might be the reason?

**Comment by melMass** [comment]
Here is what I mean:
![image](https://user-images.githubusercontent.com/7041726/143862226-d723f42a-3b8a-4d9f-afe0-1e4e91e442bb.png)

My Package file:

```json
{
    "env": [
        {
            "HTOTILIB": "$HOUDINI_USER_PREF_DIR/taichi_houdini/Libs"
        },
        {
            "PYTHONPACKSPATH": "$HOUDINI_USER_PREF_DIR/taichi_houdini/bundled-packages"
        },
        {
            "PYTHONPATH": [
                "$PYTHONPACKSPATH",
                "$HTOTILIB/python",
                "$HTOTILIB/python/taichi_elements"
            ]
        }
    ],
    "path": "$HTOTILIB"
}
```

**Comment by YuCrazing** [comment]
Hi, @melMass, I can get the same error on MacOS. Since we never test taichi-houdini on MacOS before, there can be some compatibility problem.  I need some time to figure out the reason, I will notice you as soon as possible if I make any progress.

**Comment by melMass** [comment]
> Hi, @melMass, I can get the same error on MacOS. Since we never test taichi-houdini on MacOS, there can be some compatibility problem.  I need some time to figure out the reason, I will notice you as soon as possible if I make any progress.

Thanks I'll look into it this weekend as well
