### ISSUE TITLE
Error for mpm_element_xxx

### ISSUE THREAD

**Issue by Jingzheng-Li** [taichi-dev/taichi_houdini#18]
Dear Taichi staff, I recently run taichi_houdini and found that all the "mpm_element_xxx.hipnc" Houdini file will get the error "AttributeError: module 'taichi' has no attribute 'require_version", such that

```
Python error: Traceback (most recent call last):
File "<stdin>", line 4, in <module>
File "C:\Program Files\Side Effects Software\Houdini 19.5.303\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "F:\jingzheng\taichi\TAICHI_HOUDINI\taichi_houdini\Libs\python\mpm_solver_shell.py", line 3, in <module>
from taichi_elements.engine.mpm_solver import MPMSolver
File "C:\Program Files\Side Effects Software\Houdini 19.5.303\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "F:\jingzheng\taichi\TAICHI_HOUDINI\taichi_houdini\Libs\python\taichi_elements\engine\__init__.py", line 1, in <module>
from . import mpm_solver
File "C:\Program Files\Side Effects Software\Houdini 19.5.303\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "F:\jingzheng\taichi\TAICHI_HOUDINI\taichi_houdini\Libs\python\taichi_elements\engine\mpm_solver.py", line 10, in <module>
ti.require_version(0, 7, 10)
File "C:\Users/jinzheng/AppData/Local/Programs/Python/Python39/Lib/site-packages\taichi\__init__.py", line 82, in __getattr__
raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'require_version'
```

My Houdini version is 19.5.303, taichi version 1.1.0, python 3.9.13. Could you please teach me how to fix the error? Many thanks in advance

**Comment by Jingzheng-Li** [comment]
I have fixed this problem. it seems that Taichi_Houdini use an old version taichi_element. If you update the version, then everything will be fine (at least for taichi-v1.1.0) .

**Comment by YuCrazing** [comment]
Thanks for fixing this problem (and I apologize for this late reply)! Could you submit your fixing as a PR (pull request)? We'll be happy to merge this fixing into the master branch. :)

**Comment by dongx17-THU** [comment]
@Jingzheng-Li 
I have the same problem. Did you use taichi_houdini successfully? Do I just need to update the taichi_element library?Thanks！
